apiVersion: v2
name: myapp
description: A Helm chart for deploying myapp to Kubernetes
type: application
version: 1.0.0
appVersion: '1.0.0'
home: https://github.com/myorg/myapp
sources:
  - https://github.com/myorg/myapp
maintainers:
  - name: DevOps Team
    email: devops@myorg.com
keywords:
  - web
  - api
  - microservice
annotations:
  category: Application
  licenses: Apache-2.0

dependencies:
  - name: postgresql
    version: 12.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: nginx
    version: 13.2.23
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
