#!/bin/bash
# pf-enterprise-config.sh - Advanced PF configuration for enterprise deployment

set -euo pipefail

# Configuration variables
WAN_IF="em0"
LAN_IF="em1"
DMZ_IF="em2"
MGMT_IF="em3"
LAN_NET="192.168.1.0/24"
DMZ_NET="192.168.10.0/24"
MGMT_NET="192.168.100.0/24"

generate_enterprise_pf_conf() {
    cat > /etc/pf.conf << 'EOF'
# PF Enterprise Configuration
# Generated by PF Enterprise Manager

#========================================
# MACROS
#========================================
wan_if = "em0"
lan_if = "em1"
dmz_if = "em2"
mgmt_if = "em3"

# Networks
lan_net = "192.168.1.0/24"
dmz_net = "192.168.10.0/24"
mgmt_net = "192.168.100.0/24"
vpn_net = "10.0.0.0/16"

# Services
web_ports = "{ 80, 443 }"
mail_ports = "{ 25, 465, 587, 993, 995 }"
ssh_port = "22"

#========================================
# TABLES
#========================================
table <private_nets> { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8 }
table <bruteforce> persist
table <malware_ips> persist file "/etc/pf/malware_ips.txt"
table <allowed_ssh> persist file "/etc/pf/allowed_ssh.txt"
table <geo_block_cn> persist file "/etc/pf/geo_block_cn.txt"
table <geo_block_ru> persist file "/etc/pf/geo_block_ru.txt"
table <whitelist_ips> persist file "/etc/pf/whitelist_ips.txt"

#========================================
# OPTIONS
#========================================
set timeout { tcp.first 120, tcp.established 86400 }
set timeout { tcp.closing 60, tcp.finwait 45, tcp.closed 90 }
set timeout { udp.first 60, udp.single 30, udp.multiple 120 }
set timeout { icmp.first 20, icmp.error 10 }
set timeout { other.first 60, other.single 30, other.multiple 60 }
set timeout { frag 30 }
set timeout { interval 10 }
set timeout { src.track 0 }

set limit states 100000
set limit src-nodes 50000
set limit frags 25000
set limit table-entries 200000

set optimization normal
set block-policy return
set loginterface $wan_if
set fingerprints "/etc/pf.os"

# Skip localhost
set skip on lo0

#========================================
# SCRUB RULES
#========================================
# Scrub all traffic for security
match in all scrub (no-df reassemble tcp random-id)
match out all scrub (reassemble tcp random-id)

# Specific WAN scrubbing
match in on $wan_if scrub (no-df max-mss 1440)

#========================================
# NAT RULES
#========================================
# Outbound NAT for LAN
nat on $wan_if from $lan_net to any -> ($wan_if)

# Outbound NAT for DMZ
nat on $wan_if from $dmz_net to any -> ($wan_if)

# Port forwards for DMZ services
rdr on $wan_if proto tcp from any to ($wan_if) port 80 -> 192.168.10.10 port 80
rdr on $wan_if proto tcp from any to ($wan_if) port 443 -> 192.168.10.10 port 443
rdr on $wan_if proto tcp from any to ($wan_if) port 25 -> 192.168.10.20 port 25

#========================================
# FILTER RULES
#========================================

# Default policies
block all
block return-rst in on $wan_if proto tcp all
block return-icmp in on $wan_if proto udp all
block in quick on $wan_if from <private_nets> to any
block in quick on $wan_if from <malware_ips> to any
block in quick from <geo_block_cn> to any
block in quick from <geo_block_ru> to any

# Anti-spoofing
antispoof for $wan_if inet
antispoof for $lan_if inet
antispoof for $dmz_if inet

# Loopback
pass quick on lo0 all

# ICMP
pass inet proto icmp from any to ($wan_if) icmp-type { echoreq, unreach }
pass inet proto icmp from $lan_net to any icmp-type { echoreq, unreach, timex }

# Management access
pass in on $mgmt_if proto tcp from $mgmt_net to ($mgmt_if) port { ssh, https } \
    flags S/SA modulate state \
    (max-src-conn 10, max-src-conn-rate 5/60, overload <bruteforce> flush global)

# SSH with rate limiting and whitelisting
pass in on $wan_if proto tcp from <allowed_ssh> to ($wan_if) port ssh \
    flags S/SA modulate state \
    (max-src-conn 3, max-src-conn-rate 2/60, overload <bruteforce> flush global)

# DMZ services from Internet
pass in on $wan_if proto tcp from any to 192.168.10.10 port $web_ports \
    flags S/SA modulate state \
    (max-src-conn 100, max-src-conn-rate 20/60)

pass in on $wan_if proto tcp from any to 192.168.10.20 port $mail_ports \
    flags S/SA modulate state \
    (max-src-conn 50, max-src-conn-rate 10/60)

# LAN to Internet
pass out on $wan_if proto tcp from $lan_net to any port { 21, 22, 53, 80, 443, 993, 995 } \
    flags S/SA modulate state

pass out on $wan_if proto udp from $lan_net to any port { 53, 123 } \
    modulate state

# LAN to DMZ (specific services only)
pass in on $lan_if proto tcp from $lan_net to $dmz_net port $web_ports \
    flags S/SA modulate state

# DMZ to Internet (limited)
pass out on $wan_if proto tcp from $dmz_net to any port { 53, 80, 443, 25, 587 } \
    flags S/SA modulate state

pass out on $wan_if proto udp from $dmz_net to any port { 53, 123 } \
    modulate state

# Block DMZ to LAN
block in on $dmz_if from $dmz_net to $lan_net

# Logging rules for security events
pass in log on $wan_if proto tcp from any to ($wan_if) port { 21, 23, 135, 139, 445 }
block return in log on $wan_if proto tcp from any to any port { 1433, 3389, 5900 }

# Rate limiting for brute force protection
block in quick from <bruteforce> to any

EOF
}

setup_pf_tables() {
    echo "Setting up PF tables..."

    # Create tables directory
    mkdir -p /etc/pf

    # Download and setup malware IP list
    fetch -o /tmp/malware_ips.txt "https://lists.blocklist.de/lists/all.txt" || \
    curl -o /tmp/malware_ips.txt "https://lists.blocklist.de/lists/all.txt" || true

    if [[ -f /tmp/malware_ips.txt ]]; then
        # Filter and format for PF
        grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' /tmp/malware_ips.txt > /etc/pf/malware_ips.txt
    else
        touch /etc/pf/malware_ips.txt
    fi

    # Setup SSH whitelist
    cat > /etc/pf/allowed_ssh.txt << 'EOF'
# SSH allowed IPs
192.168.100.0/24
10.0.0.0/16
# Add trusted IP ranges here
EOF

    # Setup geo-blocking lists (example for China)
    cat > /etc/pf/geo_block_cn.txt << 'EOF'
# China IP ranges (example - use proper geolocation data)
1.2.4.0/22
1.2.8.0/21
1.4.1.0/24
1.4.2.0/23
EOF

    # Setup geo-blocking lists (example for Russia)
    cat > /etc/pf/geo_block_ru.txt << 'EOF'
# Russia IP ranges (example - use proper geolocation data)
5.8.0.0/19
5.34.192.0/18
5.39.0.0/18
5.44.0.0/18
EOF

    # Setup whitelist
    cat > /etc/pf/whitelist_ips.txt << 'EOF'
# Whitelisted IPs
192.168.0.0/16
10.0.0.0/8
172.16.0.0/12
EOF
}

configure_pf_logging() {
    echo "Configuring PF logging..."

    # Create pflog interface
    ifconfig pflog0 create 2>/dev/null || true
    ifconfig pflog0 up

    # Start pflogd
    pflogd -s 160 -i pflog0 -f /var/log/pflog

    # Setup log rotation
    cat > /etc/newsyslog.conf.d/pf.conf << 'EOF'
# PF log rotation
/var/log/pflog    644  7   1000  *   B   /var/run/pflogd.pid  30
EOF

    # Setup syslog for PF
    echo "local0.*    /var/log/pf.log" >> /etc/syslog.conf
    service syslogd restart
}

setup_pf_monitoring() {
    echo "Setting up PF monitoring..."

    # Create monitoring script
    cat > /usr/local/bin/pf-monitor.sh << 'EOF'
#!/bin/bash
# PF monitoring script

LOG_FILE="/var/log/pf-monitor.log"
ALERT_THRESHOLD=1000

log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> $LOG_FILE
}

check_state_table() {
    current_states=$(pfctl -si | grep "current entries" | awk '{print $3}')
    if [[ $current_states -gt $ALERT_THRESHOLD ]]; then
        log_message "WARNING: High state table usage: $current_states"
        # Send alert (implement your alerting mechanism)
    fi
}

check_blocked_packets() {
    blocked_packets=$(pfctl -si | grep "packets blocked" | awk '{print $3}')
    log_message "INFO: Blocked packets: $blocked_packets"
}

analyze_pflog() {
    # Analyze recent pflog entries for patterns
    tcpdump -nr /var/log/pflog -c 100 2>/dev/null | \
    awk '/blocked/ {print $0}' | \
    tail -10 >> $LOG_FILE
}

main() {
    log_message "Starting PF monitoring check"
    check_state_table
    check_blocked_packets
    analyze_pflog
}

main "$@"
EOF

    chmod +x /usr/local/bin/pf-monitor.sh

    # Add cron job for regular monitoring
    echo "*/5 * * * * /usr/local/bin/pf-monitor.sh" | crontab -
}

optimize_pf_performance() {
    echo "Optimizing PF performance..."

    # Kernel tuning for PF
    cat >> /etc/sysctl.conf << 'EOF'
# PF Performance Tuning
net.pf.states_hashsize=32768
net.pf.src_nodes_hashsize=32768
net.pf.frags_hashsize=8192

# Network performance
net.inet.ip.forwarding=1
net.inet6.ip6.forwarding=1
net.inet.tcp.blackhole=2
net.inet.udp.blackhole=1
net.inet.tcp.delayed_ack=0

# Buffer sizes
kern.ipc.maxsockbuf=16777216
net.inet.tcp.sendspace=65536
net.inet.tcp.recvspace=65536
EOF

    # Apply sysctl settings
    sysctl -f /etc/sysctl.conf
}

validate_pf_configuration() {
    echo "Validating PF configuration..."

    # Test configuration syntax
    if pfctl -nf /etc/pf.conf; then
        echo "PF configuration syntax is valid"
    else
        echo "ERROR: PF configuration syntax errors found"
        exit 1
    fi

    # Check for common misconfigurations
    if grep -q "pass.*any.*any" /etc/pf.conf; then
        echo "WARNING: Overly permissive rules found"
    fi

    # Verify tables exist
    for table in malware_ips allowed_ssh geo_block_cn geo_block_ru; do
        if [[ ! -f "/etc/pf/${table}.txt" ]]; then
            echo "WARNING: Table file /etc/pf/${table}.txt not found"
        fi
    done
}

main() {
    echo "Setting up enterprise PF configuration..."

    # Generate configuration
    generate_enterprise_pf_conf

    # Setup tables
    setup_pf_tables

    # Configure logging
    configure_pf_logging

    # Setup monitoring
    setup_pf_monitoring

    # Optimize performance
    optimize_pf_performance

    # Validate configuration
    validate_pf_configuration

    # Load configuration
    pfctl -f /etc/pf.conf

    # Enable PF
    pfctl -e

    echo "Enterprise PF configuration completed successfully"
}

main "$@"