-- Create role hierarchy
CREATE ROLE DATA_ENGINEER;
CREATE ROLE DATA_ANALYST;
CREATE ROLE DATA_SCIENTIST;

-- Grant database privileges
GRANT USAGE ON DATABASE ANALYTICS TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS.SALES TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS.SALES TO ROLE DATA_ANALYST;

-- Grant future privileges
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS.SALES TO ROLE DATA_ANALYST;

-- Create functional roles
GRANT ROLE DATA_ANALYST TO USER john_doe;