-- Monitor credit consumption by warehouse
SELECT
    WAREHOUSE_NAME,
    DATE(START_TIME) as DATE,
    SUM(CREDITS_USED) as DAILY_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME, DATE(START_TIME)
ORDER BY DATE DESC, DAILY_CREDITS DESC;