; Development debug settings
[/Script/Engine.Engine]
bUseFixedFrameRate=False
GameViewportClientClassName=/Script/Engine.GameViewportClient

[Core.Log]
LogTemp=Verbose
LogBlueprintUserMessages=Verbose
LogExec=Warning