apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    version: v1
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: user-service
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user-service
spec:
  hosts:
  - user-service
  http:
  - match:
    - headers:
        version:
          exact: v2
    route:
    - destination:
        host: user-service
        subset: v2
  - route:
    - destination:
        host: user-service
        subset: v1